
 http://localhost:3000/

 
 send request
 POST http://localhost:3000/api HTTp/1.1
 content-type: application/json

##
DELETE http://localhost:3000/teams

###
http://localhost:3000/teams/

###
PUT http://localhost:3000/teams/ HTTP/1.1
content-type: application/json

